### ISSUE TITLE
XE: PIP fails to install PEXPECT

### ISSUE THREAD

**Issue by dfhawthorne** [dfhawthorne/oracle-db-build#6]
```
TASK [Use PIP to install PEXPECT on OL 7+ systems] *************************************
fatal: [xe.yaocm.id.au]: FAILED! => {"changed": false, "cmd": ["/bin/pip2", "install", "-U", "pexpect"], "msg":
```
Full message is:
```
:stderr: Traceback (most recent call last):
  File "/bin/pip2", line 9, in <module>
    load_entry_point('pip==21.0.1', 'console_scripts', 'pip2')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/pip-21.0.1-py2.7.egg/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
```

**Comment by dfhawthorne** [comment]
This issue seems to be related to "[pip install on Python 2 fails with SyntaxError: sys.stderr.write(f"ERROR: {exc}") #9500](https://github.com/pypa/pip/issues/9500)".

The solution is to use https://bootstrap.pypa.io/2.7/get-pip.py .

**Comment by dfhawthorne** [comment]
Wrote `files/validate_pip2.sh` to check:
1. PIP2 exists
2. `pip2 --version` doesn't fail

If either of these fail, download the fix from https://bootstrap.pypa.io/2.7/get-pip.py and apply it as `root` user.

**Comment by dfhawthorne** [comment]
The Ansible code to implement this fix can be found in the file, [ol7_tasks.yml](https://github.com/dfhawthorne/oracle-db-build/blob/main/ol7_tasks.yml).
